#!/usr/bin/env bash
# configure additional NGINX servers
	
#install Nginx
apt-get -y update
apt-get -y install nginx

#set up firewall
sudo ufw allow 'Nginx HTTP'

# make dir for serving webpages and grant permissions
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
	
#create index page and 404 error page
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
	

sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

sed -i "/listen 80 default_server;/a error_page 404 /404.html;" /etc/nginx/sites-available/default

sed -i '14a \\tadd_header X-Served-By '"${HOSTNAME}"';' /etc/nginx/nginx.conf

#restart after updatin settings
service nginx restart
