#!/usr/bin/env bash
# configure two new NGINX servers so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
	
#install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

#set up uwf firewall
sudo ufw allow 'Nginx HTTP'

#make repective dirs and grand permissions for easy access
sudo mkdir -p /var/www/html /var/www/error
sudo chmod -R 755 /var/www
	
#index page and error 404 page
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

	
#redirects
sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

sed -i "/listen 80 default_server;/a error_page 404 /404.html;" /etc/nginx/sites-available/default

#adds an 'x-Served-By'<hostname> header to the HTTP section of the config file
sed -i '14a \\tadd_header X-Served-By '"${HOSTNAME}"';' /etc/nginx/nginx.conf

service nginx restart
