#!/usr/bin/env bash
# configure additional NGINX servers
	
#install Nginx
apt-get -y update
apt-get -y install nginx

#set up firewall
sudo ufw allow 'Nginx HTTP'

# make dir for serving webpages and grant permissions
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
	
#create index page and 404 error page
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
	
#configure servers
"server {
		listen 80 default_server;
		listen [::]:80 default_server;
		root /var/www/html;
		index index.html index.htm index.nginx-debian.html
		server_name_;
		add_header X-Served-By \$hostname;
		location / {
			try_files \$uri \$uri/ =404;
		}
		if (\$request_filename ~ redirect_me){
			rewrite ^ https://alphaziro.tech/ permanent;
		}
		error_page 404 /error_404.html;
		location = /error_404.html {
			internal;
		}
}"

#shellcheck disable=SC2154
echo "$server_config" | sudo tee '/etc/nginx/sites-enabled/default' > /dev/null

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
